services:
  db:
    image: postgres
    volumes:
      - ./.ignore/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spotter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: ["celery", "-A", "settings", "worker", "--loglevel=info"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis