# Generated by Django 5.1.1 on 2024-09-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image URL'),
        ),
    ]
