# Generated by Django 5.1.1 on 2024-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External ID'),
        ),
    ]
