# Generated by Django 5.1.1 on 2024-09-18 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('role', models.CharField(blank=True, max_length=55, null=True, verbose_name='Role')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('isbn', models.CharField(blank=True, max_length=55, null=True, verbose_name='ISBN')),
                ('isbn13', models.CharField(blank=True, max_length=55, null=True, verbose_name='ISBN13')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher')),
                ('publication_date', models.DateField(null=True, verbose_name='Publication Date')),
                ('format', models.CharField(blank=True, max_length=55, null=True, verbose_name='Format')),
                ('series_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Series Name')),
                ('series_position', models.CharField(blank=True, max_length=55, null=True, verbose_name='Series Position')),
                ('language', models.CharField(blank=True, max_length=55, null=True, verbose_name='Language')),
                ('image_url', models.CharField(blank=True, max_length=55, null=True, verbose_name='Image URL')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Reviews Count')),
                ('fans_count', models.IntegerField(default=0, verbose_name='Fans Count')),
                ('ratings_count', models.IntegerField(default=0, verbose_name='Rating Count')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
                ('authors', models.ManyToManyField(through='books.AuthorBook', to='authors.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
