# Generated by Django 5.1.1 on 2024-09-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='fans_count',
        ),
    ]
