# Generated by Django 5.1.1 on 2024-09-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_fans_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External ID'),
        ),
    ]
